### ISSUE TITLE
Adding person parameter error in Data_final

### ISSUE THREAD

**Issue by CarolinaFellinghauer** [lindsayevanslee/whomds#4]
Would it be possible to not only save the person parameter estimates but also their measurement error? that would be helpful for the analysis of the children scales - think the low reliability is due to the super skewed distributions - with the error we could recompute our own reliability estimate - like if the distribution was normal for example [that should be ok - error and estimate are score specific not distribution dependent but large amount of estimates are found in the lower/lowest score range (where error is also higher) - so that decreases the estimate a bit 'dramatically' .

**Comment by lindsayevanslee** [comment]
@CarolinaFellinghauer Can you suggest the code you would use to capture the measurement error? The person ability estimates are calculated in the `rasch_model()` function: https://github.com/lindsayevanslee/whomds/blob/master/R/rasch_model.R

I feel like the measurement error output would be more suitable in a more intermediate file like `PersonPara.csv` instead of `Data_final.csv`, do you agree?

**Comment by CarolinaFellinghauer** [comment]
suggestion - 

either 

do not bother  because I just found the PersonPara.csv file were the requested theta se is in.... 

or 

otherwise, to have it all in Datawabilities.csv we could try:

person_par <- person_parameters$theta.table  [this is in the rasch_model function and from here...]

person_par <- cbind(pid = rownames(person_par$theta.table), person_par$theta.table)
person_par_se <- cbind(pid = names(person_par$se.theta$NAgroup1), se_theta = person_par$se.theta$NAgroup1)
person_par <- merge(person_par, person_par_se, by = "pid")
